version: "3.8"

services:
  sqlite3:
    image: keinos/sqlite3:latest
    stdin_open: true
    tty: true
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    volumes:
      - ./db/:/root/db/
  app:
    depends_on:
      - sqlite3
    build: ./spring-boot-btc-monitor
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:sqlite:$MYSQLDB_DATABASE",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.database-platform" : "com.ThinkLink.config.SQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "myconfig.minvalue" : "$MIN",
        "myconfig.maxvalue" : "$MAX",
        "myconfig.to" : "$TO",
        "myconfig.from" : "$FROM",
        "smtp.host" : "$HOST",
        "smtp.port" : "$PORT",
        "smtp.ssl" : "$SSL",
        "smtp.tls" : "$TLS",
        "smtp.user" : "$USRNM",
        "smtp.password" : "$PASSWORD",
        "myconfig.uri" : "$URI"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
